// TODO: add copyright
:prjname: Speed-Grillon
:sysname: Système {prjname}
:lf: Loïc Fejoz
:jn: Jérémie Nevin
:hk: Hamza Karzouz
:title: Cahier des charges utilisateurs - {prjname}
:doctype: article
:description: 
:Author: {lf}

= {title}

== Introduction

Ce document sert de référence à la conception du {sysname}. En
cela, il explicite et synthétise les besoins exprimés lors des
réunions et ceux recueillis dans les documents suivant :

- TODO référencer les documents externes existants

== Présentation du système

=== Finalité, Mission et Objectifs 

La finalité du {sysname} est d'informer l'utilisateur de l'écart entre
sa vitesse actuelle et une vitesse cible.

Sa mission principale est de permettre à l'utilisateur d'avoir une vitesse
régulière. En particulier dans un contexte de conduite automobile,
cela permet de :

- économiser du carburant,
- avoir un vitesse inférieure à la vitesse limite imposer par le
  code de la route.


=== Cycle de vie et Parties Prenantes

==== Cycle de vie
//TODO

[[partiesprenantes]]
==== Parties prenantes
- Concepteurs : {jn}, {hk}
- Fabricant : 
- [[conducteur]] Utilisateur final : Conducteur automobile
- Mainteneurs :
- Acheteurs : 
- Transporteur :

=== Contexte d'utilisation

==== Contexte de conduite automobile

Le contexte principal du {sysname} est l'intérieur d'une voiture.

==== Autres contextes

Le système pourrait être détourné de son usage premier afin d'être
utilisé dans d'autres contextes comme, par exemple, en course à
pied. En effet, lors des entrainements, il est important pour un
coureur d'avoir un rythme régulier. Le {sysname} pourrait dés lors
être adapté à un tel usage.

Ces autres contextes ne devront être pris en compte que lorsqu'un
compromis restreindrait de tels usages.

== Concept opérationel
//////////////////////////////////////////
Indiquer ici le comment et le qui. C'est à dire le concept du
système mais de manière plus abstraites que les scénarios.
//////////////////////////////////////////

[[scenarios]]
== Scénarios
//////////////////////////////////////////
Décrire ici les séquences d'utilisation du système, ie le où et le
quand.
//////////////////////////////////////////

[[requirements]]
== Exigences
//////////////////////////////////////////
Ajouter dans cette partie les exigences utilisateurs en suivant le
schéma suivant : 
req----
.U1
Description ::
    Le {sysname} 
SMART::
    Oui/Non
Auteur ::
    {lf}
Source ::
    
Partie prenante ::
    <<conducteur>>
Exigence parent ::
    
Exigence filles ::
    
req----
//////////////////////////////////////////


=== Entrées/Sorties
//////////////////////////////////////////
Penser ici aux exigences d'interface, d'IHM, interopérabilité, etc.
//////////////////////////////////////////

=== Performance
//////////////////////////////////////////
Penser ici aux exigences de maintenance, d'efficacité, d'efficience,
de sûreté de fonctionnement, de sécurité, etc.
//////////////////////////////////////////

=== Technologie
//////////////////////////////////////////
Penser ici aux contraintes technologiques, de portabilité, aux
standards mécaniques ou de connectique, de design et de fabrication,
réglementaires, réutilisabilité, etc.
//////////////////////////////////////////

=== Coût
//////////////////////////////////////////
Penser ici aux coûts de fabrication, de conception, d'utilisation, de
fourniture, etc.
//////////////////////////////////////////

=== Test
//////////////////////////////////////////
Penser ici aux auto-tests, boites noires/grises/blanches, testabilité, etc.
//////////////////////////////////////////

=== Compromis
//////////////////////////////////////////
Indiquer ici comment résoudre les conflits entre exigences :
Performance/Coûts, etc.
//////////////////////////////////////////

== Glossaire

== Traçabilité

=== Matrice Parties prenantes / Exigences
//////////////////////////////////////////
Insérer ici un tableau de correspondance entre les parties prenantes
de la section <<partiesprenantes>> en regard des exigences de la
section <<requirements>>. Vérifiez que chaque partie prenante a bien
au moins une exigence.
//////////////////////////////////////////


=== Matrice Parties prenantes / Scénarios
//////////////////////////////////////////
Insérer ici un tableau de correspondance entre les parties prenantes
de la section <<partiesprenantes>> en regard des scénarios de la
section <<scenarios>>. Vérifiez que chaque partie prenante intervient
dans au moins un scénario.
//////////////////////////////////////////
