// TODO: add copyright
:prjname: Speed-Grillon
:sysname: Système {prjname}
:lf: Loïc Fejoz
:jn: Jérémie Nevin
:hk: Hamza Karzouz
:title: Cahier des charges utilisateurs - {prjname}
:doctype: article
:description: 
:Author: {lf}

= {title}

== Introduction

Ce document sert de référence à la conception du {sysname}. En
cela, il explicite et synthétise les besoins exprimés lors des
réunions et ceux recueillis dans les documents suivant :

- TODO référencer les documents externes existants

== Présentation du système

=== Finalité, Mission et Objectifs 

La finalité du {sysname} est d'informer l'utilisateur de l'écart entre
sa vitesse actuelle et une vitesse cible.

Sa mission principale est de permettre à l'utilisateur d'avoir une vitesse
régulière. En particulier dans un contexte de conduite automobile,
cela permet de :

- économiser du carburant,
- avoir un vitesse inférieure à la vitesse limite imposée par le
  code de la route.


=== Cycle de vie et Parties Prenantes

==== Cycle de vie
//TODO

[[partiesprenantes]]
==== Parties prenantes
- Concepteurs : {jn}, {hk}
- Fabricant : 
- [[conducteur]] Utilisateur final : Conducteur automobile
- Mainteneurs :
- Acheteurs : 
- Transporteur :

=== Contexte d'utilisation

==== Contexte de conduite automobile

Le contexte principal du {sysname} est l'intérieur d'une voiture.

==== Autres contextes

Le système pourrait être détourné de son usage premier afin d'être
utilisé dans d'autres contextes comme, par exemple, en course à
pied. En effet, lors des entraînements, il est important pour un
coureur d'avoir un rythme régulier. Le {sysname} pourrait dés lors
être adapté à un tel usage.

Ces autres contextes ne devront être pris en compte que lorsqu'un
compromis restreindrait de tels usages.

== Concept opérationnel
//////////////////////////////////////////
Indiquer ici le comment et le qui. C'est à dire le concept du
système mais de manière plus abstraites que les scénarios.
//////////////////////////////////////////


[[scenarios]]
== Scénarios
//////////////////////////////////////////
Décrire ici les séquences d'utilisation du système, ie le où et le
quand.
//////////////////////////////////////////



[[requirements]]
== Exigences
//////////////////////////////////////////
Ajouter dans cette partie les exigences utilisateurs en suivant le
schéma suivant : 
req----
.UXXX
Description ::
    Le {sysname} 
Justification::
    
Critères d'acceptation::
    
SMART::
    Oui/Non
Auteur ::
    {lf}
Source ::
    
Partie prenante ::
    <<conducteur>>
Exigence parent ::
    
Exigence filles ::
    
req----
//////////////////////////////////////////


=== Entrées/Sorties
//////////////////////////////////////////
Penser ici aux exigences d'interface, d'IHM, interopérabilité, etc.
//////////////////////////////////////////

req----
.U1
Description ::
    En fonctionnement, le {sysname} doit fournir au <<conducteur>> le signe de l'écart entre la vitesse
    cible et la vitesse réelle.
Justification::
    Le <<conducteur>> doit savoir s'il faut ralentir ou accélérer.
Critères d'acceptation::
    Le <<conducteur>> reçoit l'information dés que l'écart est
    supérieur à 0.5km/h.
SMART::
    Oui/Non
Auteur ::
    {lf}
Source ::
    {lf}
Partie prenante ::
    <<conducteur>>
Exigence parent ::
    
Exigence filles ::
    
req----

req----
.U2
Description ::
    En fonctionnement, le {sysname} doit fournir au <<conducteur>> la grandeur de l'écart entre la vitesse
    cible et la vitesse réelle.
Justification::
    Le <<conducteur>> doit savoir s'il est éloigné de la consigne afin
    de jauger de la grandeur de l'action à prendre en fonction de son environnement.
Critères d'acceptation::
    Le <<conducteur>> reçoit l'information dés que l'écart est
    supérieur à 0.5km/h.
SMART::
    Oui/Non
Auteur ::
    {lf}
Source ::
    {lf}
Partie prenante ::
    <<conducteur>>
Exigence parent ::
    
Exigence filles ::
    
req----

req----
.U3
Description ::
    En mode réglage, le <<conducteur>> peut établir une liste de vitesses consignes de références.
Justification::
    Cela permet au conducteur de référencer les vitesses limites les
    plus utilisées dans son pays.
Critères d'acceptation::
    TODO
SMART::
    Oui/Non
Auteur ::
    {lf}
Source ::
    {lf}
Partie prenante ::
    <<conducteur>>
Exigence parent ::
    
Exigence filles ::
    
req----

req----
.U4
Description ::
    En fonctionnement, le <<conducteur>> peut remplacer la consigne
    courante par la valeur la plus grande de sa liste préétablie
    immédiatement inférieure à la consigne actuelle.
Justification::
    Cela limite le temps d'interaction avec le système.
Critères d'acceptation::
    TODO
SMART::
    Oui/Non
Auteur ::
    {lf}
Source ::
    {lf}
Partie prenante ::
    <<conducteur>>
Exigence parent ::
    
Exigence filles ::
    
req----

req----
.U5
Description ::
    En fonctionnement, le <<conducteur>> peut remplacer la consigne
    courante par la valeur la plus petite de sa liste préétablie
    immédiatement supérieure à la consigne actuelle.
Justification::
    Cela limite le temps d'interaction avec le système.
Critères d'acceptation::
    TODO
SMART::
    Oui/Non
Auteur ::
    {lf}
Source ::
    {lf}
Partie prenante ::
    <<conducteur>>
Exigence parent ::
    
Exigence filles ::
    
req----

=== Performance
//////////////////////////////////////////
Penser ici aux exigences de maintenance, d'efficacité, d'efficience,
de sûreté de fonctionnement, de sécurité, etc.
//////////////////////////////////////////

req----
.U6
Description ::
    Le {sysname} doit fournir une information à jour toutes 2 secondes.
Justification::
    C'est un compromis entre le temps de réaction du conducteur et l'inertie de
    la voiture.
Critères d'acceptation::
    2s +/- 1s.
SMART::
    Oui/Non
Auteur ::
    {lf}
Source ::
    {lf}
Partie prenante ::
    <<conducteur>>
Exigence parent ::
    
Exigence filles ::
    
req----

=== Technologie
//////////////////////////////////////////
Penser ici aux contraintes technologiques, de portabilité, aux
standards mécaniques ou de connectique, de design et de fabrication,
réglementaires, réutilisabilité, etc.
//////////////////////////////////////////

=== Coût
//////////////////////////////////////////
Penser ici aux coûts de fabrication, de conception, d'utilisation, de
fourniture, etc.
//////////////////////////////////////////

req----
.U7
Description ::
    Le {sysname} doit coûter moins de 68€ à construire.
Justification::
    C'est le prix d'une amende 3ème classe tarif normal (dépassement 20km/h).
Critères d'acceptation::
    Le prix est au coût complet sauf réutilisation de matériel déjà
    possédé par le <<conducteur>>.
SMART::
    Oui/Non
Auteur ::
    {lf}
Source ::
    
Partie prenante ::
    <<conducteur>>
Exigence parent ::
    
Exigence filles ::
    
req----

=== Test
//////////////////////////////////////////
Penser ici aux auto-tests, boites noires/grises/blanches, testabilité, etc.
//////////////////////////////////////////

=== Compromis
//////////////////////////////////////////
Indiquer ici comment résoudre les conflits entre exigences :
Performance/Coûts, etc.
//////////////////////////////////////////

== Glossaire

== Traçabilité

=== Matrice Parties prenantes / Exigences
//////////////////////////////////////////
Insérer ici un tableau de correspondance entre les parties prenantes
de la section <<partiesprenantes>> en regard des exigences de la
section <<requirements>>. Vérifiez que chaque partie prenante a bien
au moins une exigence.
//////////////////////////////////////////


=== Matrice Parties prenantes / Scénarios
//////////////////////////////////////////
Insérer ici un tableau de correspondance entre les parties prenantes
de la section <<partiesprenantes>> en regard des scénarios de la
section <<scenarios>>. Vérifiez que chaque partie prenante intervient
dans au moins un scénario.
//////////////////////////////////////////
